import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Provider, useDispatch, useSelector} from 'react-redux';
import {store, fetchInteractions, createInteraction, updateInteraction, sendChat} from './store/store';
import './style.css';

const empty = {hcp_name:'', interaction_type:'Meeting', topics:'', materials_shared:'', samples_discussed:'', outcome:'Neutral', objections:'', follow_up:'', sentiment:'Neutral', ai_summary:'', raw_note:''};
function FormPanel(){const d=useDispatch(); const [form,setForm]=useState(empty); const submit=e=>{e.preventDefault(); d(createInteraction(form)); setForm(empty)}; const set=(k,v)=>setForm({...form,[k]:v}); return <section className="card"><h2>Structured Log Interaction</h2><form onSubmit={submit} className="grid"><input required placeholder="HCP Name" value={form.hcp_name} onChange={e=>set('hcp_name',e.target.value)}/><select value={form.interaction_type} onChange={e=>set('interaction_type',e.target.value)}><option>Meeting</option><option>Call</option><option>Email</option><option>Conference</option></select><textarea placeholder="Topics discussed" value={form.topics} onChange={e=>set('topics',e.target.value)}/><textarea placeholder="Materials shared / samples discussed" value={form.materials_shared} onChange={e=>set('materials_shared',e.target.value)}/><select value={form.outcome} onChange={e=>set('outcome',e.target.value)}><option>Positive</option><option>Neutral</option><option>Negative</option></select><textarea placeholder="Objections" value={form.objections} onChange={e=>set('objections',e.target.value)}/><textarea placeholder="Follow-up actions" value={form.follow_up} onChange={e=>set('follow_up',e.target.value)}/><button>Save Interaction</button></form></section>}
function ChatPanel(){const d=useDispatch(); const {chat,loading}=useSelector(s=>s.crm); const [msg,setMsg]=useState(''); const submit=()=>{ if(!msg.trim())return; d(sendChat(msg)); setMsg('')}; return <section className="card chat"><h2>AI Assistant Chat</h2><p className="hint">Example: “Met Dr Sharma, discussed diabetes product, interested but wants pricing next week.”</p><div className="messages">{chat.map((c,i)=><div key={i} className="bubble"><b>{c.tool_used}</b><p>{c.reply}</p></div>)}{loading&&<div className="bubble">AI is thinking...</div>}</div><div className="chatbox"><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Describe HCP interaction..." onKeyDown={e=>e.key==='Enter'&&submit()}/><button onClick={submit}>Ask AI</button></div></section>}
function Table(){const d=useDispatch(); const {items}=useSelector(s=>s.crm); const [edit,setEdit]=useState(null); return <section className="card full"><h2>Interaction History</h2><table><thead><tr><th>HCP</th><th>Type</th><th>Outcome</th><th>Summary</th><th>Follow-up</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.hcp_name}</td><td>{x.interaction_type}</td><td>{x.outcome}</td><td>{x.ai_summary || x.topics}</td><td>{x.follow_up}</td><td><button onClick={()=>setEdit(x)}>Edit</button></td></tr>)}</tbody></table>{edit&&<div className="modal"><div className="modalbox"><h2>Edit Interaction</h2><input value={edit.hcp_name} onChange={e=>setEdit({...edit,hcp_name:e.target.value})}/><textarea value={edit.ai_summary||''} onChange={e=>setEdit({...edit,ai_summary:e.target.value})}/><textarea value={edit.follow_up||''} onChange={e=>setEdit({...edit,follow_up:e.target.value})}/><button onClick={()=>{d(updateInteraction({id:edit.id,data:edit})); setEdit(null)}}>Update</button><button className="ghost" onClick={()=>setEdit(null)}>Cancel</button></div></div>}</section>}
function App(){const d=useDispatch(); useEffect(()=>{d(fetchInteractions())},[]); return <main><header><h1>AI-First CRM: HCP Log Interaction</h1><p>React + Redux frontend, FastAPI backend, LangGraph agent, Groq Gemma2-9B LLM and SQL database.</p></header><div className="layout"><FormPanel/><ChatPanel/></div><Table/></main>}
createRoot(document.getElementById('root')).render(<Provider store={store}><App/></Provider>);
